### ISSUE TITLE
Masternode

### ISSUE THREAD

**Issue by vsgarry** [binariumpay/binarium#11]
Здравствуйте, как настроить мастерноду для майнинга binarium.

**Comment by binariumpay** [comment]
Здравствуйте. Конфигурация в целом аналогична DASH, и описана здесь: https://github.com/binariumpay/binarium/blob/master/doc/masternode_conf.md
Только понадобится 1000 BIN.
Для контроля можно использовать Sentinel: https://github.com/binariumpay/sentinel
