### ISSUE TITLE
Как начать майнинг

### ISSUE THREAD

**Issue by ssvrus** [binariumpay/binarium#2]
Доброго времени суток. Скачали и установил кошелек. Что делать дальше, чтобы начать майнинг? Увидел, что есть различного рода настройки, урл пулов, и тд. Майнинг вроде вклечен, но прогресс как-то возможно отслеживать? Спасибо.

**Comment by Realharon** [comment]
Начать майнить очень просто. Майнинг из кошелька ничем не отличается от майнинга любых других криптовалют, разве что не надо майнеров устанавливать, так мы встроили пул-майнинг прямо в кошелёк.

Там где в настройках "URL пула", указываете адрес пула, например наш официальный пул: `stratum+tcp://pool.binarium.money:3001`
Но мы советуем пул `stratum+tcp://pool.rplant.xyz:3334` ([https://pool.rplant.xyz/](https://pool.rplant.xyz/))

В поле "Пользователь" указываете свой адрес кошелька для входящих платежей. В поле "Алгоритм" должно быть `Binarium_hash_v1`, он итак стоит по умолчанию.

"Приоритет CPU"* - прриоритет процесса майнинга в системе над другими процессами, по умолчанию стоит 0 (низкий), трогать в общем-то не нужно. 

Аффинность** - количество ядер процессора, которое вы хотите задействовать. Мы рекомендуем указывать количество физических ядер (Не HT-ядер) минус 1.

И не забудьте поставить галочку "Включить майнинг в пуле". После чего вам будет предложено перезагрузить кошелёк с новыми настройками. Управлять майнингом из кошелька можно нажатием индикатора (зелёный или красный) внизу кошелька.

Через некоторое время вы [появитесь здесь](https://pool.binarium.money/workers) и разумеется, начнёте получать выплаты (сейчас выплаты производятся раз в сутки, по достижении суммы в 10 BIN). Скоро выведем более подробную статистику, иной пока нет.

\* Всего приоритетов в Windows 6 (от 0 до 5 соответственно.): низкий, ниже среднего, средний, выше среднего, высокий и реального времени. 
Узнать больше о приоритетах процессов Windows вы: [можете здесь](https://docs.microsoft.com/en-us/windows/desktop/ProcThread/scheduling-priorities)

\*\* Например у вас процессор INTEL Core i7 7700. У этого процессора 4 физических ядра и 8 потоков, то есть 4 физических и 4 HT (HyperThreading) ядра. То есть указывать вам имеет смысл 3. Тогда майнинг не будет мешать работе компьютера, разве что игры будут тормозить чуть больше.
