### ISSUE TITLE
Не запускается кошелёк

### ISSUE THREAD

**Issue by gamma-aspirin** [binariumpay/binarium#3]
[debug.log](https://github.com/binariumpay/binarium/files/2449389/debug.log)

**Comment by RodionKarimov** [comment]
Судя по логу, он у вас запускался до этого. Возможно, у вас повреждены файлы Block-Chain. Попробуйте в папке данных удалить все файлы, кроме wallet.dat и запустить кошелёк по новой.

**Comment by gamma-aspirin** [comment]
RodionKarimov <notifications@github.com> писал(а) в своём письме Fri, 05  
Oct 2018 15:31:16 +0700:

>
> Судя по логу, он у вас запускался до этого. Возможно, у вас повреждены  
> файлы Block-Chain. Попробуйте в папке данных удалить все файлы, >кроме  
> wallet.dat и запустить кошелёк по новой.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Спасибо. Запустился.
-- 
Написано с помощью почтового клиента Opera: http://www.opera.com/mail/
