### ISSUE TITLE
где блокчейн скачать?

### ISSUE THREAD

**Issue by ilsawa** [binariumpay/binarium#4]
Не синхронизируется бумажник собранный из исходников.
Дошёл до 2400 блоков и стоит
> binarium-cli getblockchaininfo
> {
>   "chain": "main",
>   "blocks": 24000,
>   "headers": 24000,
>   "bestblockhash": "0000001060efc21297c8e609379def0ab9460b2596f4ab10323e9b01152e6a62",
>   "difficulty": 0.002967176199058834,
>   "mediantime": 1520401573,
>   "verificationprogress": 0.1734767484297527,
>   "chainwork": "0000000000000000000000000000000000000000000000000000006b4de9991c",
>   "pruned": false,
>   "softforks": [
>     {
>       "id": "bip34",
>       "version": 2,
>       "enforce": {
>         "status": true,
>         "found": 1000,
>         "required": 750,
>         "window": 1000
>       },
>       "reject": {
>         "status": true,
>         "found": 1000,
>         "required": 950,
>         "window": 1000
>       }
>     },
>     {
>       "id": "bip66",
>       "version": 3,
>       "enforce": {
>         "status": true,
>         "found": 1000,
>         "required": 750,
>         "window": 1000
>       },
>       "reject": {
>         "status": true,
>         "found": 1000,
>         "required": 950,
>         "window": 1000
>       }
>     },
>     {
>       "id": "bip65",
>       "version": 4,
>       "enforce": {
>         "status": true,
>         "found": 1000,
>         "required": 750,
>         "window": 1000
>       },
>       "reject": {
>         "status": true,
>         "found": 1000,
>         "required": 950,
>         "window": 1000
>       }
>     }
>   ],
>   "bip9_softforks": [
>     {
>       "id": "csv",
>       "status": "active"
>     },
>     {
>       "id": "dip0001",
>       "status": "started"
>     }
>   ]
> }

Коннекты есть
> binarium-cli getconnectioncount
> 8

**Comment by Realharon** [comment]
Если клиент перестал или не хочет синхронизироваться, может помочь его перезапуск.
